# Generated by Django 4.2.4 on 2023-08-24 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_income',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_income',
            name='person',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
