# Generated by Django 4.2.4 on 2023-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_income_date_user_income_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_income',
            name='purpose',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
