# Generated by Django 4.2.4 on 2023-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_extra_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_income',
            name='extra_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
