# Generated by Django 4.2.4 on 2023-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_expense_date_alter_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='val',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='val',
            field=models.FloatField(default=0),
        ),
    ]
