# Generated by Django 4.2.4 on 2023-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_paymentmode_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='val',
            field=models.FloatField(),
        ),
    ]
