# Generated by Django 4.2.4 on 2023-09-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_category_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='val',
            field=models.FloatField(default=0),
        ),
    ]
